### ISSUE TITLE
Should be able to search careers

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/www.canonical.com#237]
Most job sites give you a search for role and allows you to filter by location. It would be nice to add these features to the careers section of the site.

**Comment by anthonydillon** [comment]
No one has triaged this so I will go ahead and do it myself. I don't think triage should be done by the person that reported the issue.

**Comment by crownvik71** [comment]
7862865137

**Comment by anthonydillon** [comment]
Going to descope this one due to lack of resource.

**Comment by anasereijo** [comment]
@anthonydillon I think this is something good to have on careers page. Is this still possible to have as we use greenhouse? 

I will move this issue to careers [epic](https://github.com/ubuntudesign/web-squad/issues/926).

**Comment by pmahnke** [comment]
closing, this will be addressed in the c.c refresh
