### ISSUE TITLE
Update client logos on /services 'A selection of customers using our services' section

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/www.canonical.com#297]
## Enhancement

Currently in the process of updating client logos to use our new alignment template, so they sit on an imaginary baseline which will give logos:

- A comparable visual weight
- Fit in a given height / width
- Reduces elongated or very thin logos to appear a lot smaller

### Page
Update logos on: https://www.canonical.com/services

### Logos to update

Wikimedia - https://assets.ubuntu.com/v1/207128eb-2018-logo-wikimedia.svg
Bloomberg - https://assets.ubuntu.com/v1/9ae8ff55-2018-logo-bloomberg.svg
T-Mobile - https://assets.ubuntu.com/v1/93ecb091-2018-logo-t-mobile.svg
Intel - https://assets.ubuntu.com/v1/94ea495b-2018-logo-Intel.svg
China Telecom - https://assets.ubuntu.com/v1/34a1f30e-2018-logo-china-telecom.svg
eBay - https://assets.ubuntu.com/v1/675af314-2018-logo-eBay.svg
Microsoft Azure - https://assets.ubuntu.com/v1/6d027c12-2018-logo-Microsoft-Azure.svg
Samsung - https://assets.ubuntu.com/v1/a31edc0b-2018-logo-samsung.svg
Google - https://assets.ubuntu.com/v1/2d54fa27-logo-google--snapcraft-homepage.svg
NTT - https://assets.ubuntu.com/v1/94da9f2a-2018-logo-NTT.svg
Mercado Libre - https://assets.ubuntu.com/v1/cad7a966-2018-logo-mercado-libre.svg
Cisco - https://assets.ubuntu.com/v1/8a4d26de-2018-logo-cisco.svg

**Comment by kwm14** [comment]
We need to fix `p-inline-images` component for this update to work. Blocked for now.

**Comment by anasereijo** [comment]
closing this as a new website is being designed
