### ISSUE TITLE
404 page on forms sub site is from the past

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/www.canonical.com#324]
## Summary

Visit a page that doesn't exist, you'll get sent through a time tunnel to a website from the past.

## Process

Visit https://forms.canonical.com/this_page_does_not_exist

## Current and expected result

See below screenshot. I'd expect something that looks vaugely like canonical.com.

## Screenshot

![image](https://user-images.githubusercontent.com/1841272/50967143-1c792d00-14cf-11e9-8e9d-bf949968e6a5.png)

**Comment by pmahnke** [comment]
@popey I will pass this on to neil messenbird, no one knows how to update forms.c.c  perhaps we need another solution?
