### ISSUE TITLE
Broken link from the document

### ISSUE THREAD

**Issue by feldbauer** [canonical-web-and-design/www.canonical.com#365]
## Summary

Broken Link

## Process

https://help.landscape.canonical.com/FAQ#What_ports_does_the_Landscape_client_use_for_communication_with_the_server.3F

Is there an on-site version of Landscape?

Yes, the Landscape Dedicated Server is installed on-site on your hardware and provides all the same management and monitoring features of Landscape. All system information is transmitted over your network so no access to the public Internet is required. Details on the Dedicated Server can be found here: http://www.canonical.com/enterprise-services/ubuntu-advantage/landscape/dedicated-edition

The link above is broken

## Current and expected result

404: Page not found

Sorry, we can't find the page you're looking for.

If you think this is an error on our site, please file a bug.

I expected the enterprise-services page to come up.

## Screenshot

[if relevant, include a screenshot]

**Comment by anthonydillon** [comment]
A redirect from the canonical page should go to somewhere useful. For bonus points update the landscape page to point directly to the useful page.

**Comment by feldbauer** [comment]
I guess I was confused about this. When I clicked on support from the page, it brought me here and I thought I would open a support ticket here for Canonical to fix. This was an informational post only. I have no affiliation with landscape and or Canonical.

Closing this thread - sorry for the confusion.
